/**:
  ros__parameters:
    common/lid_topic:  "/os_cloud_node/points"
    common/imu_topic:  "/os_cloud_node/imu"
    common/time_sync_en: false       # ONLY turn on when external time synchronization is really not possible

    preprocess/lidar_type: 3         # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR
    preprocess/scan_line: 64
    preprocess/blind: 4.0

    mapping/acc_cov: 0.1
    mapping/gyr_cov: 0.1
    mapping/b_acc_cov: 0.0001
    mapping/b_gyr_cov: 0.0001
    mapping/fov_degree: 180.0
    mapping/det_range: 150.0
    mapping/extrinsic_T: [ 0.0, 0.0, 0.0 ]
    mapping/extrinsic_R: [ 1.0, 0.0, 0.0,
                           0.0, 1.0, 0.0,
                           0.0, 0.0, 1.0]

    publish/scan_publish_en: true       # 'false' will close all the point cloud output
    publish/dense_publish_en: true      # false will low down the points number in a global-frame point clouds scan.
    publish/scan_bodyframe_pub_en: true # output the point cloud scans in IMU-body-frame
